export const INDEXES: {
  ALL_TREATMENT_STATISTICS: string;
  ALL_TREATMENT_STATISTICS_BY_TREATMENT_HASH: string;
} = {
  ALL_TREATMENT_STATISTICS: 'allTreatmentStatistics',
  ALL_TREATMENT_STATISTICS_BY_TREATMENT_HASH: 'allTreatmentStatisticsByTreatmentHash'
};
